### PR TITLE
Unit tests are now running using Pester 5

### LINKED ISSUE #40: Convert tests to Pester 5

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Unit tests are now running using Pester 5 (issue #40).
- Excludes the PowerShell module script file _DscResource.Common.psm1_ located
  in folder _source_ from the HQRM testing.
- Now code coverage is uploaded to codecov.io.

#### This Pull Request (PR) fixes the following issues
- Fixes #40

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/41)

### CODE REVIEW

**Comment by johlju** [comment]
This PR is waiting for pipeline fixes to support Pester 5.

**Comment by PlagueHO** [comment]
We'll need to release the new sampler version after that.

**Comment by johlju** [comment]
Yep, and then wait for the HQRM tests to be resolved (so they can be run in both Pester 4 and Pester 5).

**Comment by johlju** [comment]
Closing and reopening

**Comment by johlju** [comment]
I will fix the bugs in the unit tests. After that the HQRM tests are dependent on the PR https://github.com/dsccommunity/DscResource.Test/pull/76.

**Comment by johlju** [comment]
The failing test works when run individually or if run before all other tests. Discussing this in #testing in Slack.

```
PS /mnt/c/source/DscResource.Common> Invoke-Pester ./tests/Unit/Public/Assert-BoundParameter.Tests.ps1,./tests/Unit/Public/Test-IsNanoServer.Tests.ps1
Starting discovery in 2 files.
Discovery finished in 229ms.
[+] /mnt/c/source/DscResource.Common/tests/Unit/Public/Assert-BoundParameter.Tests.ps1 319ms (214ms|85ms)
[-] Context Test-IsNanoServer.When the current computer is a Datacenter Nano server failed
 CommandNotFoundException: Could not find Command Get-CimInstance
[-] Context Test-IsNanoServer.When the current computer is a Standard Nano server failed
 CommandNotFoundException: Could not find Command Get-CimInstance
[-] Context Test-IsNanoServer.When the current computer is not a Nano server failed
 CommandNotFoundException: Could not find Command Get-CimInstance
Tests completed in 3.53s
Tests Passed: 6, Failed: 3, Skipped: 0 NotRun: 0
BeforeAll \ AfterAll failed: 3
  - Test-IsNanoServer.When the current computer is a Datacenter Nano server
  - Test-IsNanoServer.When the current computer is a Standard Nano server
  - Test-IsNanoServer.When the current computer is not a Nano server
PS /mnt/c/source/DscResource.Common> Invoke-Pester ./tests/Unit/Public/Test-IsNanoServer.Tests.ps1,./tests/Unit/Public/Assert-BoundParameter.Tests.ps1
Starting discovery in 2 files.
Discovery finished in 233ms.
VERBOSE:
VERBOSE:
VERBOSE:
[+] /mnt/c/source/DscResource.Common/tests/Unit/Public/Test-IsNanoServer.Tests.ps1 281ms (29ms|42ms)
[+] /mnt/c/source/DscResource.Common/tests/Unit/Public/Assert-BoundParameter.Tests.ps1 320ms (219ms|79ms)
Tests completed in 604ms
Tests Passed: 9, Failed: 0, Skipped: 0 NotRun: 0
```
 We can workaround the issue by skipping this test file on Linux and macOS. But this seems like a bug in Pester 5.

**Comment by johlju** [comment]
The failing test have been refactored. This PR is now waiting for the HQRM tests to work in Pester 5.

**Comment by johlju** [comment]
There seems to be a bug in the HQRM tests that need to be sorted before this PR can be merged.

**Comment by johlju** [comment]
@PlagueHO do you have time to review this? No hurry at al. It is a bit large. But there have been no changes to code, just the tests have been modified to work with Pester 5.

**Comment by johlju** [comment]
Now the correct code coverage is reported, so the missing code coverage have to be resolved in another PR (unless I messed up and accidently removed a test).

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Just some minor tweaks but looking good - I love the new test init structure (so much improved over the old one :grin:). 

> Reviewed 25 of 28 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-:-Mcry9YnBz_5X1YVIDJJ:bpn7dqe)* status: all files reviewed, 10 unresolved discussions (waiting on @johlju)

___
*[cocdecov.yml, line 3 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrt1HgCf_hnUFxnC5U:-Mcrt1HgCf_hnUFxnC5V:b-yxg5ni) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/cocdecov.yml#L3)):*
> ```YAML
> codecov:
>   require_ci_to_pass: no
>   # master should be the baseline for reporting
> ```

Should be main here
___
*[tests/QA/module.tests.ps1, line 24 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcru--j2ccyUoyBWTa1:-Mcru--j2ccyUoyBWTa2:bf433rx) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L24)):*
> ```PowerShell
> 
> Describe 'General module control' -Tags 'FunctionalQuality' {
>     It 'imports without errors' {
> ```

Message should be 'Should import without errors'
___
*[tests/QA/module.tests.ps1, line 63 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruCx8EwChtjLzWD5f:-McruCx8EwChtjLzWD5g:b-7wiz2w) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L63)):*
> ```PowerShell
>             if ($ErrorActionPreference -ne 'Stop')
>             {
>                 Write-Warning -Message "ScriptAnalyzer not found!"
> ```

Single quotes here.
___
*[tests/QA/module.tests.ps1, line 67 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruEfq8HCdViEVoB2j:-McruEfq8HCdViEVoB2k:b-7wiz2w) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L67)):*
> ```PowerShell
>             else
>             {
>                 throw "ScriptAnalyzer not found!"
> ```

Single quotes here.
___
*[tests/QA/module.tests.ps1, line 73 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruHdCANpwnoyeJPAQ:-McruHdCANpwnoyeJPAR:b5bstcr) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L73)):*
> ```PowerShell
> 
>     It "<Name> has a unit test" -TestCases $testCases {
>         Get-ChildItem "tests\" -Recurse -Include "$Name.Tests.ps1" | Should -Not -BeNullOrEmpty
> ```

Single quotes here and also needs parameter name
___
*[tests/QA/module.tests.ps1, line 77 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruM_h-7-boR8JJbiy:-McruM_h-7-boR8JJbiz:bfxe224) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L77)):*
> ```PowerShell
> 
>     It "Script Analyzer for <Name>" -TestCases $testCases -Skip:(-not $scriptAnalyzerRules) {
>         $functionFile = Get-ChildItem -path $sourcePath -Recurse -Include "$Name.ps1"
> ```

Path parameter name needs caps
___
*[tests/QA/module.tests.ps1, line 125 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcruu2ABNr-6FcQsAhu:-Mcruu2ABNr-6FcQsAhv:b6s85p8) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L125)):*
> ```PowerShell
>         $astSearchDelegate = { $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }
>         $parsedFunction = $AbstractSyntaxTree.FindAll( $astSearchDelegate, $true ) |
>             Where-Object -FilterScript { $_.Name -eq $Name }
> ```

```powershell
{
    $_.Name -eq $Name
}
```
___
*[tests/QA/module.tests.ps1, line 143 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McrukClDslF--zT0869:-McrukCm0kuX-4cg4JXX:bdau2fb) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L143)):*
> ```PowerShell
>         $astSearchDelegate = { $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }
>         $parsedFunction = $AbstractSyntaxTree.FindAll( $astSearchDelegate, $true ) |
>             Where-Object -FilterScript { $_.Name -eq $Name }
> ```

Can we use:
```powershell
{
    $_.Name -eq $Name
}
```
___
*[tests/QA/module.tests.ps1, line 147 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrub-64JSfktKXFymk:-Mcrub-64JSfktKXFyml:ba4wmsu) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L147)):*
> ```PowerShell
>         $functionHelp = $parsedFunction.GetHelpContent()
> 
>         $parameters = $parsedFunction.Body.ParamBlock.Parameters.Name.VariablePath.ForEach{ $_.ToString() }
> ```

Nitpick: ForEach({})
___
*[tests/Unit/Public/Compare-DscParameterState.Tests.ps1, line 991 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrwrpr0WhK3LhM2FPJ:-Mcrwrpr0WhK3LhM2FPK:brayidi) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/Unit/Public/Compare-DscParameterState.Tests.ps1#L991)):*
> ```PowerShell
> 
>                 It 'Should return $false for PSCredential InDesiredState' {
>                     $script:result.where({$_.Property -eq 'PSCredential'}).InDesiredState | Should -BeFalse
> ```

Where should be capital 'W' - also can we use:
```powershell
$script:result.Where({
    $_.Property -eq 'PSCredential'
}).InDesiredState | Should -BeFalse
```

and throughout.

**Review by johlju — COMMENTED** [review]
> Reviewed 24 of 28 files at r1, 1 of 3 files at r3, 1 of 1 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/41)* status: all files reviewed, 10 unresolved discussions (waiting on @PlagueHO)

___
*[cocdecov.yml, line 3 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrt1HgCf_hnUFxnC5U:-MctS9wKE6uZ6S0LB3Hq:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/cocdecov.yml#L3)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be main here
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 24 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcru--j2ccyUoyBWTa1:-MctSBiS1ZYj8OcRqnBT:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Message should be 'Should import without errors'
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 63 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruCx8EwChtjLzWD5f:-MctSDKg8yHt87e3UGMs:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L63)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Single quotes here.
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 67 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruEfq8HCdViEVoB2j:-MctSE133SdPLuy14D2D:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L67)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Single quotes here.
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 73 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruHdCANpwnoyeJPAQ:-MctSFM1BIoAcf5adMdd:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L73)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Single quotes here and also needs parameter name
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 77 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McruM_h-7-boR8JJbiy:-MctT4ZM6k3liOz9dz1M:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L77)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Path parameter name needs caps
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 125 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcruu2ABNr-6FcQsAhu:-MctT73H7SFp9k3nOe08:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L125)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

```powershell
{
    $_.Name -eq $Name
}
```
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 143 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-McrukClDslF--zT0869:-MctTKaO2YXSRClHRiFL:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L143)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we use:
```powershell
{
    $_.Name -eq $Name
}
```
</blockquote></details>

Done.
___
*[tests/QA/module.tests.ps1, line 147 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrub-64JSfktKXFymk:-MctTLSr5tGHhFgKZj6E:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/QA/module.tests.ps1#L147)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: ForEach({})
</blockquote></details>

Done.
___
*[tests/Unit/Public/Compare-DscParameterState.Tests.ps1, line 991 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-Mcrwrpr0WhK3LhM2FPJ:-MctTNj_EnCxCpoik5So:b-qncnqn) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/6205fadd651e6d43eacaaa38b415cf155933cc9b/tests/Unit/Public/Compare-DscParameterState.Tests.ps1#L991)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Where should be capital 'W' - also can we use:
```powershell
$script:result.Where({
    $_.Property -eq 'PSCredential'
}).InDesiredState | Should -BeFalse
```

and throughout.
</blockquote></details>

Done.  And fixed everywhere... A LOT of them ;)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/41#-:-Md444Dp5VELpmHDlBO_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
