### PR TITLE
Adds cmdlets needed for NetworkingDsc

### PR DESCRIPTION
**Pull request by johlju**
##### Added
- Added cmdlet `ConvertTo-CimInstance`. _This cmdlet comes from NetworkingDsc._
- Added cmdlet `ConvertTo-Hashtable`. _This cmdlet comes from NetworkingDsc._

##### Changed

- Update the README.md with new cmdlet documentation format.
  following the style guideline.
- Update to use HQRM tests from the DscResource.Test module.
- Update the repository to use the latest version of ModuleBuilder.
- Update to use the latest pipeline files.
- BREAKING CHANGE: Updated the cmdlet `Test-DscParameterState` to match
  the one in the module NetworkingDsc which have been extended with for
  example checking credentials and types. This might be a breaking change
  in certain scenarios, for example the type checking if on by default.
  _This change is required to be able to move the module NetworkingDsc_
  _to use this module._

#### This Pull Request (PR) fixes the following issues
None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/28)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO can you review this one, then I can help move NetworkingDsc over to DscResource.Common.

**Comment by PlagueHO** [comment]
Will review today. Would like to get the Parameter State functions over first before moving networking dsc. I'll try submitting those later on today too as I have the latest copies.

**Comment by johlju** [comment]
If you mean Test-DscParameterState you can push changes to this PR if you like since this moves the one in NetworkingDsc. :) But do as you like :)

**Comment by PlagueHO** [comment]
Oh right- I thought I was commenting on another one! :grin: Didn't realize you'd already been working on Test-DscParameterState. 

Did you copy all the code straight over from NetworkingDsc, including the Unit Tests?

**Comment by PlagueHO** [comment]
Oh, I see you did - I'll just review this then - haha.

**Comment by johlju** [comment]
Yes I copied them 1:1 from NetworkingDsc so that NetworkingDsc can use DscResource.Common. It’s a breaking change for other repos if for example the type checking fails. But those repos can resolve that by pin an earlier version.

**Pull request merged**
