### PR TITLE
`Test-ModuleExist`: New public command

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- `Test-ModuleExist`
  - Checks if a PowerShell module with a specified name is available in a
    PSModulePath.

#### This Pull Request (PR) fixes the following issues
None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Minor nitpicks :grinning:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-:-NqP0X6T1wooigBCfcDv:b-nqhqul)* status: all files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[`source/Public/Test-ModuleExist.ps1` line 15 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqOwI6K91tRfZm9h8wR:-NqOwI6K91tRfZm9h8wS:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/source/Public/Test-ModuleExist.ps1#L15)):*
> ```PowerShell
> 
>     .PARAMETER Name
>         The name of the module to check if available.
> ```





_Suggestion:_
```PowerShell
The name of the module to check is available.
```
___
*[`source/Public/Test-ModuleExist.ps1` line 21 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqOz_vA6UjU4um4gMwU:-NqOz_vA6UjU4um4gMwV:b4norki) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/source/Public/Test-ModuleExist.ps1#L21)):*
> ```PowerShell
>         filter the modules based on the scope.
> 
>     .PARAMETER Path
> ```

It looks like this searches through this folder and subfolders. Would it be worth mentioning that the search does include subfolders as well?
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 109 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-cl6Aa5zgtMSvyhE:-NqP-cl6Aa5zgtMSvyhF:b45h) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L109)):*
> ```PowerShell
>     Context 'When checking if a module with a specific preview version exists on the machine' {
>         Context 'When module is unavailable' {
>             Context 'When the module exist with the wrong prerelease string' {
> ```





_Suggestion:_
```PowerShell
Context 'When the module exists but has a different prerelease string' {
```
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 129 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-nIeEjXxWBV7gT-6:-NqP-nIeEjXxWBV7gT-7:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L129)):*
> ```PowerShell
>             }
> 
>             Context 'When the module exist with an empty prerelease string' {
> ```





_Suggestion:_
```PowerShell
Context 'When the module exists but has an empty prerelease string' {
```
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 149 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-sTz3kzJROn7qLqp:-NqP-sTz3kzJROn7qLqq:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L149)):*
> ```PowerShell
>             }
> 
>             Context 'When the module exist with no prerelease string' {
> ```





_Suggestion:_
```PowerShell
Context 'When the module exists with no prerelease string' {
```
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 186 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-zT2DcUPrb4vscWV:-NqP-zT2DcUPrb4vscWW:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L186)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module with a specific path exist' {
> ```





_Suggestion:_
```PowerShell
Context 'When checking if a module with a specific path exists' {
```
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 219 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP03l32f9Wi0od4Xf7:-NqP03l4AwHp-m7RISC5:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L219)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module in Scope CurrentUser exist' {
> ```





_Suggestion:_
```PowerShell
Context 'When checking if a module in Scope CurrentUser exists' {
```
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 251 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP05uy1VQDDy7YOHcT:-NqP05uy1VQDDy7YOHcU:undefined) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L251)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module in Scope AllUsers exist' {
> ```





_Suggestion:_
```PowerShell
Context 'When checking if a module in Scope AllUsers exists' {
```

**Review by johlju — COMMENTED** [review]
Thanks for the proof reading! I hope the additions make it more clear on one of your comments. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-:-NqRQu0J1ebhtThodJmW:bh69wju)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[`source/Public/Test-ModuleExist.ps1` line 15 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqOwI6K91tRfZm9h8wR:-NqRN--VEiXn1Szg9InZ:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/source/Public/Test-ModuleExist.ps1#L15)):*
> ```PowerShell
> 
>     .PARAMETER Name
>         The name of the module to check if available.
> ```

Done.
___
*[`source/Public/Test-ModuleExist.ps1` line 21 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqOz_vA6UjU4um4gMwU:-NqRN1Kq08XsDYrcx7_r:b-n2cg2w) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/source/Public/Test-ModuleExist.ps1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It looks like this searches through this folder and subfolders. Would it be worth mentioning that the search does include subfolders as well?
</blockquote></details>

Done. It does not? :thinking: It checks each module's path returned from `Get-Module -ListAvailable` if the specified path match the module's path. I added text and example trying to explain that. 
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 109 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-cl6Aa5zgtMSvyhE:-NqRQoWKDVoFxRn4D1T4:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L109)):*
> ```PowerShell
>     Context 'When checking if a module with a specific preview version exists on the machine' {
>         Context 'When module is unavailable' {
>             Context 'When the module exist with the wrong prerelease string' {
> ```

Done.
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 129 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-nIeEjXxWBV7gT-6:-NqRQpU_9jWvojD4PIxa:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L129)):*
> ```PowerShell
>             }
> 
>             Context 'When the module exist with an empty prerelease string' {
> ```

Done.
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 149 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-sTz3kzJROn7qLqp:-NqRQq8S9mCx6y5L-aFj:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L149)):*
> ```PowerShell
>             }
> 
>             Context 'When the module exist with no prerelease string' {
> ```

Done.
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 186 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP-zT2DcUPrb4vscWV:-NqRQqt48NcV3Gx4qhhf:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L186)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module with a specific path exist' {
> ```

Done.
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 219 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP03l32f9Wi0od4Xf7:-NqRQroEEWvvqnq3AM7G:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L219)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module in Scope CurrentUser exist' {
> ```

Done.
___
*[`tests/Unit/Public/Test-ModuleExist.Tests.ps1` line 251 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-NqP05uy1VQDDy7YOHcT:-NqRQsuQELJVSAgIzFbm:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/f7dfbae7cc5ade5e6f3b5f23d98247ec798c3d80/tests/Unit/Public/Test-ModuleExist.Tests.ps1#L251)):*
> ```PowerShell
>     }
> 
>     Context 'When checking if a module in Scope AllUsers exist' {
> ```

Done.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121#-:-NqTzMTCERF7S1gACVcq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Comment by johlju** [comment]
thank you @PlagueHO!

**Pull request merged**
