### PR TITLE
Adding latest version of 'Test-DscParameterState' from JeaDsc

### PR DESCRIPTION
**Pull request by raandree**
#### Pull Request (PR) description
Adding latest version of 'Test-DscParameterState' from JeaDsc.

- `Test-DscParameterState` can now handle scriptblocks.
- The parameter 'ValuesToCheck was renamed to 'Properties' but an alias was added so it is not a braking change.
- The parameter 'ExcludeProperties' was added.

#### This Pull Request (PR) fixes the following issues
NA

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/46)

### CODE REVIEW

**Comment by raandree** [comment]
What is the difference between 'Compare-ResourcePropertyState' in #48 and 'Test-DscParameterState'? Do we have two functions now doing the same thing?

**Comment by johlju** [comment]
> What is the difference between 'Compare-ResourcePropertyState' in #48 and 'Test-DscParameterState'? Do we have two functions now doing the same thing?

First I'm very happy we get this PR that updates `Test-DscParameterState` which _many_ DSC modules uses. 

The difference is that they are two different design patterns. While `Test-DscParameterState` is designed to be used only in _Test_ the `Compare-ResourcePropertyState` is designed to be used in both _Test_ and _Set (and can also be used in _Get_, but that is an edge case)_. I tried to explain it a bit here in the proposed PR; https://github.com/dsccommunity/DscResource.Common/blob/f34b8e8770d56bc5ac02a2a50cfebaa3f4677b45/README.md#compare-resourcepropertystate, but probably need a blog post around this in the future (on the todo list the PR is accepted).
This new design pattern is basically meant to handle that _Set_ does not set values that are already in desired state. Having one compare function for both _Set_ and _Test_ means there is no need to duplicate code in _Set_ to evaluate if a property should be set or not.

There are many modules that are using `Test-DscParameterState` for its resources and that will probably not change. So the other design pattern can be used for new modules/resources if a contributor/maintainer so chooses. Currently the only resources that uses this new design pattern are new resources in ActiveDirectoryDsc and SqlServerDsc. But SqlServerDsc also uses the design pattern `Test-DscParameterState` for many resources (and I don't see those being refactored).

**Comment by gaelcolas** [comment]
Really looking forward to this (& compare-), I think it will really help improve the DSC Resources quality & reduce effort in the longer run.

**Comment by johlju** [comment]
@raandree the last test is failing the tests, see review comment.

**Pull request merged**
