### PR TITLE
Added public function Assert-ElevatedUser

### LINKED ISSUE #82: Add Assert-ElevatedUser from SqlServerDsc to DscResource.Common Public Functions
### Problem description

The request to move Assert-ElevatedUser to the DscResource.Common module was created in the SqlServerDsc module under [Issue 1797](https://github.com/dsccommunity/SqlServerDsc/issues/1797). 

This function is used to assert the user is using an elevated PowerShell session, and that it could also better the entire DSC community by being included in the DscResource.Common module.

The function can be placed prior to commands that require elevated permissions, e.g. 
`...`
`Assert-ElevatedUser -ErrorAction 'Stop'`
`[Code that requires elevated permissions]`
`...`

### Verbose logs

```text
N/A
```

### How to reproduce

N/A

### Expected behavior

N/A

### Current behavior

N/A

### Suggested solution

N/A

### Operating system the target node is running

```text
N/A
```

### PowerShell version and build the target node is running

```text
N/A
```

### Module version used

```text
0.11.1
```

### PR DESCRIPTION
**Pull request by hollanjs**
#### Pull Request (PR) description
Moved `Assert-ElevatedUser` from a private function in SqlServerDsc to a public function in DscResource.Common
Original issue logged in SqlServerDsc by @johlju [Issue #1797](https://github.com/dsccommunity/SqlServerDsc/issues/1797)

#### This Pull Request (PR) fixes the following issues
- Fixes #82

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/84)

### CODE REVIEW

**Comment by hollanjs** [comment]
Please disregard - did not realize that PRs were tightly coupled with the branch they came from, so I closed them instead of updating the branch. Lesson learned!

**Comment by hollanjs** [comment]
@johlju - My PR associated with [SqlServerDsc #1979](https://github.com/dsccommunity/SqlServerDsc/issues/1797), that moves the `Assert-ElevatedUser` to the DscResource.Common module. Please let me know if it requires any additional updates or changes.

Please disregard PR #83
Being my first PRs, I didn't realize all I had to do was update my branch. Before I knew this, I had already closed and opened a new one - lesson learned!

**Comment by johlju** [comment]
@hollanjs no worries that you opened a new PR 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/84)* status: all files reviewed, 1 unresolved discussion (waiting on @hollanjs)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dscresource.common/84#-NIYM_Qk62A72COmOlMz:-NIYM_Ql3w2DCq1a7BNM:bp1ezuh) (no related file):*
In the README.md we add the documentation for the command, like syntax. Please add the new command in the correct place (alphabetical order). Unfortunatly we have not yet fixed ths to update automatically, so I usually use the comment-based help and  use `Get-Help` to get the syntax.

___

**Comment by hollanjs** [comment]
@johlju - I added the cmdlet to the README.md; tried to be as detailed as possible but also succinct since the function really only does 1 thing and doesn't take inputs.

I also corrected the 'Syntax' block for `Assert-IPAddress` since it didn't follow the other subheading formats.

**Comment by johlju** [comment]
Great! I wil review this as soon as I can., at the latest on saturday.

**Comment by johlju** [comment]
Great work @hollanjs! I will do a full release of this module, then we can review and merge the PR in SqlServerDsc.

**Pull request merged**
