### PR TITLE
Add Compare-DscParameterState based on the code of Test-DscParameterState

### PR DESCRIPTION
**Pull request by NicolasBn**
#### Pull Request (PR) description

This is a proposition to add Compare-DscParameterState function. It's based on the code of Test-DscParameterState function.
This function returns a collection of hastable with two key : Property and Compliance. 
Property contains the name of property (parameter) checked. Compliance is a boolean value who indicate if the property is in the desired state. 

Example :
```powershell
$DesiredValue = @{
    String = 'This is a string'
    int = 1
}

$CurrentValue = @{
    String = 'This is a string' 
    int = 2
 }

Compare-DscParameterState -CurrentValues $CurrentValue -DesiredValues $DesiredValue        


Name                           Value
----                           -----
Property                       String
Compliance                     True
Compliance                     False
Property                       int

```

If the DSCResource have [Reasons](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create#get-targetresource-requirements) property, we can use this function in Get-TargetResource or Get() method in Class-based resources. 
Like this : 
```powershell
$script:localizedDataClassFolder = Get-LocalizedData -DefaultUICulture en-US -FileName 'DSC_ClassFolder.strings.psd1'

[DscResource()]
class DSC_ClassFolder
{
    [DscProperty(Key)]
    [string] $Path

    [DscProperty(Mandatory)]
    [bool] $ReadOnly

    [DscProperty()]
    [bool] $Hidden

    [DscProperty()]
    [Ensure] $Ensure

    [DscProperty(NotConfigurable)]
    [bool] $Shared

    [DscProperty(NotConfigurable)]
    [String] $ShareName

    [DSC_ClassFolder] Get()
    {
        Write-Verbose -Message (
            $script:localizedData.RetrieveFolder `
                -f $this.Path
        )

        $currentState = [DSC_ClassFolder]::New()
        $currentState.Path = $this.Path

        # Using -Force to find hidden folders.
        $folder = Get-Item -Path $this.Path -Force -ErrorAction 'SilentlyContinue' |
            Where-Object -FilterScript {
                $_.PSIsContainer -eq $true
            }

        if ($folder)
        {
            Write-Verbose -Message $script:localizedData.FolderFound
            # change to function
            $isReadOnly = $this.TestFileAttribute($folder, 'ReadOnly')
            $isHidden = $this.TestFileAttribute($folder, 'Hidden')

            $folderShare = Get-SmbShare |
                Where-Object -FilterScript {
                    $_.Path -eq $this.Path
                }

            # Cast the object to Boolean.
            $isShared = [System.Boolean] $folderShare
            if ($isShared)
            {
                $smbShareName = $folderShare.Name
            }
            else
            {
                $smbShareName = $null
            }

            $currentState.Ensure = [Ensure]::Present
            $currentState.ReadOnly = $isReadOnly
            $currentState.Hidden = $isHidden
            $currentState.Shared = $isShared
            $currentState.ShareName = $smbShareName


            $valuesToCheck = @(
                'Ensure'
                'ReadOnly'
                'Hidden'
            )

            $CompareState = Compare-DscParameterState `
                -CurrentValues $currentState.ConvertToHashtable() `
                -DesiredValues $this.ConvertToHashtable() `
                -ValuesToCheck $valuesToCheck | Where-Object {$_.Compliance -eq $false }

            $currentState.reasons = switch ($CompareState)
            {
                {$_.Property -eq 'Ensure'}{
                    [Reason]@{
                        Code = '{0}:{0}:Ensure' -f $this.GetType()
                        Phrase = $script:localizedData.FolderFound
                    }
                    continue
                }
                {$_.Property -eq 'ReadOnly'}{
                    [Reason]@{
                        Code = '{0}:{0}:ReadOnly' -f $this.GetType()
                        Phrase = $script:localizedData.DontBeReadOnly
                    }
                    continue
                }
                {$_.Property -eq 'Hidden'}{
                    [Reason]@{
                        Code = '{0}:{0}:Hidden' -f $this.GetType()
                        Phrase = $script:localizedData.DontBeHidden
                    }
                    continue
                }
            }
        }
        else
        {
            $currentState.Ensure = [Ensure]::Absent
            Write-Verbose -Message $script:localizedData.FolderNotFound
            $currentState.reasons = [Reason]@{
                Code = '{0}:{0}:Ensure' -f $this.GetType()
                Phrase = $script:localizedData.FolderNotFound
            }
        }

        return $currentState
    }

    [void] Set()
    {
         ...
    }

    [bool] Test()
    {
        ...
    }
```

And we don't need to use Test-DscParameterState in Test() method if Get() is used to get the current state.
We just need to check if the result of Get() has value in Reasons property.

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56)

### CODE REVIEW

**Comment by gaelcolas** [comment]
tagging @raandree here :)

**Comment by PlagueHO** [comment]
Strange- @gaelcolas, have you come across this issue recently? https://dev.azure.com/dsccommunity/DscResource.Common/_build/results?buildId=3082&view=logs&j=842a2b08-7829-5f68-46ff-c3078c2a1071&t=b17733e1-3748-5dae-37a6-8c304e66fb21&l=74

It looks like something odd going on in the git diff command on Linux or OSX, but not 100% sure. Haven't seen this in any other projects using Sampler though.

**Review by gaelcolas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

___
*[CHANGELOG.md, line 20 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtgirA2vMSTXKQxaCx:-MKtgirA2vMSTXKQxaCy:b-gxbji5) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/CHANGELOG.md#L20)):*
> ```Markdown
> ### Changed
> 
> - Cmdlet Test-DscResourceState is now a wrapper of Compare-DscParameterState. Possible breaking change.
> ```

not a wrapper, just calling Compare.
___
*[README.md, line 151 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtgxYHEl7YBL0ZCvdP:-MKtgxYHEl7YBL0ZCvdQ:b-bqnyp7) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/README.md#L151)):*
> ```Markdown
> 
> Compare current against desired property state for any DSC resource and return
> a hashtable with the metadata from the comparison.
> ```

a collection of hashtable
___
*[README.md, line 190 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKthQQUCvP8v8nYhnf6:-MKthQQUCvP8v8nYhnf7:bbgyh4f) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/README.md#L190)):*
> ```Markdown
> }
> 
> Compare-DscParameterState -CurrentValues $currentValues -DesiredValues $desiredValues
> ```

I wonder if it's not better tot have a collection of objects instead with: PropertyName|PropertyType|Compliance?
And maybe repeat the ExpectedValue and ActualValue ?
___
*[source/Public/Compare-DscParameterState.ps1, line 168 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtp1JO9p9EgVQm172Q:-MKtp1JPA2uf15NheJ3e:b6yqpbp) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L168)):*
> ```PowerShell
>     #region CheckType of object
>     $types = 'System.Management.Automation.PSBoundParametersDictionary',
>         'System.Collections.Hashtable',
> ```

what if it's an OrderedDictionary with case insensitive keys ([ordered]@{}) ?
Make sure you have a test for that (that's what datum uses).
___
*[source/Public/Compare-DscParameterState.ps1, line 204 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtjEnG5wXdBVFT9ieA:-MKtjEnG5wXdBVFT9ieB:b1cys5s) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L204)):*
> ```PowerShell
>         $keyList = $Properties
>     }
>     if ($ExcludeProperties)
> ```

missing new line before if ()
___
*[source/Public/Compare-DscParameterState.ps1, line 321 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtnuSw99EyXDTxnAec:-MKtnuSw99EyXDTxnAed:bmec5k2) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L321)):*
> ```PowerShell
>         #endregion
>         #region Check if desired type is array, ifno Hashtable and currenttype hashtable to
>         if ($desiredType.IsArray)
> ```

hmmm. I feel like .IsArray() is too restrictive?
`if ($desiredType -is [System.Collection.Enumerable] -and $desiredType -isnot [string])`
That needs to be tested because some data types like orderedDictionary are probably enumerables too (if so exclude).
___
*[tests/Unit/Public/Compare-DscParameterState.Tests.ps1, line 22 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtqLV5EvEG59Vzxf80:-MKtqLV5EvEG59Vzxf81:b-l3hpm7) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/tests/Unit/Public/Compare-DscParameterState.Tests.ps1#L22)):*
> ```PowerShell
>         }
> 
>         Context 'When testing single values' {
> ```

Not for now, but once this PR is merged, we should add tests with Class instances to validate it works with Class DSC Resources like this: https://github.com/gaelcolas/DscStuff/blob/master/assets/ClassRsrcWithSubType2/ClassRsrcWithSubType2.psm1#L28
And if it fails, maybe just add -skip to that test until we fix the code.

**Review by gaelcolas — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56)* status: all files reviewed, 5 unresolved discussions (waiting on @johlju, @NicolasBn, and @PlagueHO)

**Review by gaelcolas — COMMENTED** [review]
Yeah the git issue was because of how the command was written. see last commit by @nicolasbn to see.
The Sampler template was updated a while ago, but after this repo was created. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-:-MKtrDrA12mNrOM7MQJX:b30wu5g)* status: all files reviewed, 5 unresolved discussions (waiting on @johlju, @NicolasBn, and @PlagueHO)

**Review by NicolasBn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56)* status: all files reviewed, 5 unresolved discussions (waiting on @gaelcolas, @johlju, and @PlagueHO)

___
*[README.md, line 151 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtgxYHEl7YBL0ZCvdP:-MKvOjyy49Od5DY3SPPI:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/README.md#L151)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

a collection of hashtable
</blockquote></details>

Done.
___
*[README.md, line 190 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKthQQUCvP8v8nYhnf6:-MKvSGTx2xz53bLNhcvq:b-4lnn23) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/README.md#L190)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

I wonder if it's not better tot have a collection of objects instead with: PropertyName|PropertyType|Compliance?
And maybe repeat the ExpectedValue and ActualValue ?
</blockquote></details>

I wondered about this point. I think we can reproduce the output as Compare-DscProperty :
Metadata Name | Type | Description
--- | --- | ---
ParameterName | `[System.String]` | The name of the property that was evaluated
Expected | The type of the property | The desired value for the property
Actual | The type of the property | The actual current value for the property
InDesiredState | `[System.Boolean]` | Returns `$true` if the expected and actual value was equal.
___
*[source/Public/Compare-DscParameterState.ps1, line 168 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtp1JO9p9EgVQm172Q:-MKvOwj19iXXkTQtCSyK:b-vz9ggk) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L168)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

what if it's an OrderedDictionary with case insensitive keys ([ordered]@{}) ?
Make sure you have a test for that (that's what datum uses).
</blockquote></details>

Indeed, OrderedDictionary isn't in supported type. 
It can be add.
This involed some modification in function. Example in line 306:
`if ($desiredValuesClean.GetType().Name -in 'HashTable', 'PSBoundParametersDictionary')`
___
*[source/Public/Compare-DscParameterState.ps1, line 204 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtjEnG5wXdBVFT9ieA:-MKvP8B1AddllplzAuUC:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L204)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

missing new line before if ()
</blockquote></details>

Done.
___
*[source/Public/Compare-DscParameterState.ps1, line 321 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtnuSw99EyXDTxnAec:-MKvPF84-uIsiEw-HEVh:bb2wp2b) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L321)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

hmmm. I feel like .IsArray() is too restrictive?
`if ($desiredType -is [System.Collection.Enumerable] -and $desiredType -isnot [string])`
That needs to be tested because some data types like orderedDictionary are probably enumerables too (if so exclude).
</blockquote></details>

This type contains lots of derived type : 

https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.ienumerable?view=net-5.0

Other proposition : 
`if ($desiredType.namespace -like 'System.Collections.*' -or $desiredType.IsArray)`

**Review by gaelcolas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56)* status: all files reviewed, 3 unresolved discussions (waiting on @gaelcolas, @johlju, @NicolasBn, and @PlagueHO)

___
*[README.md, line 190 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKthQQUCvP8v8nYhnf6:-MLssFefD0NhlxUZeKAj:b-ikznyg) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/README.md#L190)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

I wondered about this point. I think we can reproduce the output as Compare-DscProperty :
Metadata Name | Type | Description
--- | --- | ---
ParameterName | `[System.String]` | The name of the property that was evaluated
Expected | The type of the property | The desired value for the property
Actual | The type of the property | The actual current value for the property
InDesiredState | `[System.Boolean]` | Returns `$true` if the expected and actual value was equal.
</blockquote></details>

I don't understand your table. xD
but it should be a PSCustomObject with Name/ExpectedType/ActualType/InDesiredState
Optionally (command parameter switch)  add ExpectedValue and CurrentValue.
Optionally return parameters that ARE in desired State.
___
*[source/Public/Compare-DscParameterState.ps1, line 168 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtp1JO9p9EgVQm172Q:-MLsrcaa-xNyp3zfB35y:bb1hp1) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L168)):*
> oled some modification in function. Example in line 306:
> if ($desiredValuesClean.GetType().Name -in 'HashTable',
can you open an issue to handle this later, not a blocker for this PR.
___
*[source/Public/Compare-DscParameterState.ps1, line 321 at r2](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MKtnuSw99EyXDTxnAec:-MLsqu4vDVbUzRO_EVvS:bpbheil) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/1b6cf550080c0905169af948e1b357ca411ce9e4/source/Public/Compare-DscParameterState.ps1#L321)):*
<details><summary><i>Previously, NicolasBn (NicolasB) wrote…</i></summary><blockquote>

This type contains lots of derived type : 

https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.ienumerable?view=net-5.0

Other proposition : 
`if ($desiredType.namespace -like 'System.Collections.*' -or $desiredType.IsArray)`
</blockquote></details>

lets leave like this for now. I think we'll need to have better comparison logic anyway (for more complex cases).

**Review by gaelcolas — APPROVED** [review]
:lgtm:

That looks good.
There's a couple of update to make in help/text, but that's not blocking. Please create a subsequent PR with fixes.
Approving and merging, will make a release and you may use that in Sampler.

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-:-MM2UwwqA44lBRUJqaGq:b32s514)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju, @NicolasBn, and @PlagueHO)

___
*[CHANGELOG.md, line 19 at r4](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MM2TETK1R2oPMU6Dd-P:-MM2TETLEfJk4FguvmNI:b28bsgg) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/84fd87dafc1974444e8be85d3180db8d199828a0/CHANGELOG.md#L19)):*
> ```Markdown
>   The properties of psobject are Property,InDesiredState,ExpectedType,ActualType,
>   ExpectedValue and ActualValue. The IncludeInDesiredState parameter must be use to
>   add ExceptedValue and ActualValue.
> ```

Expected* (typo)
___
*[source/Public/Compare-DscParameterState.ps1, line 38 at r4](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MM2Ta2cCRvLotcxQkGS:-MM2Ta2cCRvLotcxQkGT:bulnjyg) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/84fd87dafc1974444e8be85d3180db8d199828a0/source/Public/Compare-DscParameterState.ps1#L38)):*
> ```PowerShell
> 
>     .PARAMETER IncludeInDesiredState
>         Indicates that result adds the properties in desired state.
> ```

in **the** desired state.
___
*[source/Public/Compare-DscParameterState.ps1, line 39 at r4](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MM2TdTYAH4Mn24c_U25:-MM2TdTYAH4Mn24c_U26:b-d51byl) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/84fd87dafc1974444e8be85d3180db8d199828a0/source/Public/Compare-DscParameterState.ps1#L39)):*
> ```PowerShell
>     .PARAMETER IncludeInDesiredState
>         Indicates that result adds the properties in desired state.
>         By default, this command return only the properties in not desired state.
> ```

this commands returns* only* the properties not* in desired state.
___
*[source/Public/Test-DscParameterState.ps1, line 127 at r4](https://reviewable.io/reviews/dsccommunity/dscresource.common/56#-MM2UYQI51gYeHuulXQS:-MM2UYQI51gYeHuulXQT:bkeeoez) ([raw file](https://github.com/dsccommunity/dscresource.common/blob/84fd87dafc1974444e8be85d3180db8d199828a0/source/Public/Test-DscParameterState.ps1#L127)):*
> ```PowerShell
>         [Parameter()]
>         [System.Management.Automation.SwitchParameter]
>         $IncludeInDesiredState,
> ```

Why do we need that in Test?

**Pull request merged**
