### PR TITLE
Add cmdlet Set-PSModulePath

### PR DESCRIPTION
**Pull request by johlju**
#### This Pull Request (PR) fixes the following issues
- Added cmdlet `Set-PSModulePath`.

This cmdlet helps when mocking these changes in a unit test.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.common/38)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO When you have a minute over can you review this one? 🙂

**Comment by PlagueHO** [comment]
Looks like the tests are failing @johlju :

The Help Description is missing and need to suppress a PSSA Error.

**Comment by johlju** [comment]
Fixed I hope. Forgot about that.

**Comment by johlju** [comment]
@PlagueHO Now the tests are passing 😃

**Pull request merged**
