### PR TITLE
Add public commands `Get-PSModulePath` and `Get-EnvironmentVariable`

### LINKED ISSUE #103: `Get-PSModulePath`: New command proposal
Suggest adding a new command with a mandatory parameter `FromTarget` with the type `String[]` that has a validate set of `Session`, `User`, `Machine`. The command returns the concatenated paths (separated with semi-colon) depending on what targets was passed to the parameter. Multiple targets should be able to be passed.

This command should be used by `Set-PSModulePath` as suggested in issue #102.
 
The code suggestion:

```
            <#
                Get the environment variables from all targets session, user and machine.
                Casts the value to System.String to convert $null values to empty string.
            #>
            $modulePathSession = [System.String] [System.Environment]::GetEnvironmentVariable('PSModulePath')
            $modulePathUser = [System.String] [System.Environment]::GetEnvironmentVariable('PSModulePath', 'User')
            $modulePathMachine = [System.String] [System.Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')

            $modulePath = $modulePathSession, $modulePathUser, $modulePathMachine -join ';'

            $modulePathArray = $modulePath -split ';' |
                Where-Object -FilterScript {
                    -not [System.String]::IsNullOrEmpty($_)
                } |
                Sort-Object -Unique

            $modulePath = $modulePathArray -join ';'
```

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description

- New public commands.
  - `Get-EnvironmentVariable` - Get a specific environment variable from a
    specific environment variable target.
  - `Get-PSModulePath` - Get the the PSModulePath from one or more environment
    variable targets - [Issue #103](https://github.com/dsccommunity/DscResource.Common/issues/103)

#### This Pull Request (PR) fixes the following issues
- Fixes #103

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [x] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[`README.md` line 723 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNWWvv2TaBMz7cDuHn:-NSNWWvv2TaBMz7cDuHo:be2sr0u) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/README.md#L723)):*
> ```Markdown
> 
> Returns the environment variable PSModulePath from the specified target.
> If more than one target are provided only the unique paths will be
> ```

Could this be changed to:
If more than one target is provided the return will contain all the concatenation of all unique paths from the targets.
___
*[`source/Public/Get-PSModulePath.ps1` line 8 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNWy8B5Mba2jJN4sJD:-NSNWy8B5Mba2jJN4sJE:b-tu4sha) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/source/Public/Get-PSModulePath.ps1#L8)):*
> ```PowerShell
>     .DESCRIPTION
>         Returns the environment variable PSModulePath from the specified target.
>         If more than one target are provided only the unique paths will be
> ```

See previous comment on clarification of behavior.
___
*[`source/Public/Get-PSModulePath.ps1` line 41 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNXOFz3g-Tq0cKlVjs:-NSNXOFz3g-Tq0cKlVjt:b-lns59o) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/source/Public/Get-PSModulePath.ps1#L41)):*
> ```PowerShell
>     )
> 
>     $modulePathSession = $null
> ```

nit: I don't think (I couldn't find) a style guideline on this, but you could use (although not sure it's the most clear syntax). Will leave it up to you:



_Suggestion:_
```PowerShell
    $modulePathSession = $modulePathUser = $modulePathMachine = $null
```
___
*[`tests/Unit/Public/Get-PSModulePath.Tests.ps1` line 86 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNYXbR6ugardlMLgmo:-NSNYXbR6ugardlMLgmp:by9x2vg) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/tests/Unit/Public/Get-PSModulePath.Tests.ps1#L86)):*
> ```PowerShell
>         }
>     }
> ```

Nit: remove blank line.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[`README.md` line 723 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNWWvv2TaBMz7cDuHn:-NSQDusE1wB3z2QSjwH2:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/README.md#L723)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could this be changed to:
If more than one target is provided the return will contain all the concatenation of all unique paths from the targets.
</blockquote></details>

Done.
___
*[`source/Public/Get-PSModulePath.ps1` line 8 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNWy8B5Mba2jJN4sJD:-NSQDw8SBW7nJMrKh8jW:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/source/Public/Get-PSModulePath.ps1#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See previous comment on clarification of behavior.
</blockquote></details>

Done.
___
*[`source/Public/Get-PSModulePath.ps1` line 41 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNXOFz3g-Tq0cKlVjs:-NSQDySh60XBJPo1Dy2w:bfviu9o) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/source/Public/Get-PSModulePath.ps1#L41)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: I don't think (I couldn't find) a style guideline on this, but you could use (although not sure it's the most clear syntax). Will leave it up to you:
</blockquote></details>

Done. We can do it this way too. Changed. :slightly_smiling_face: 
___
*[`tests/Unit/Public/Get-PSModulePath.Tests.ps1` line 86 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-NSNYXbR6ugardlMLgmo:-NSQE6oQCdJuPG3FzA-y:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.Common/blob/21732715e118ecd8a04409d8956c6f6e20e08628/tests/Unit/Public/Get-PSModulePath.Tests.ps1#L86)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nit: remove blank line.
</blockquote></details>

Done.

**Comment by johlju** [comment]
@PlagueHO thanks for the review! Hopefully it good to be sign-off on now. 🙂

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104#-:-NSbSfBf6uWLgtlKnC8C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
